all:
  hosts:
    master:
      ansible_host: 10.0.1.10
      ip: 10.0.1.10
      access_ip: 10.0.1.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/new.rsa
    node1:
      ansible_host: 10.0.2.11
      ip: 10.0.2.11
      access_ip: 10.0.2.11
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/new.rsa
    node2:
      ansible_host: 10.0.3.12
      ip: 10.0.3.12
      access_ip: 10.0.3.12
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/new.rsa
    teamcity-server:
      ansible_host: 10.0.1.44
      ip: 10.0.1.44
      access_ip: 10.0.1.44
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/new.rsa
    teamcity-agent:
      ansible_host: 10.0.1.34
      ip: 10.0.1.34
      access_ip: 10.0.1.34
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/ubuntu/.ssh/new.rsa
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
