---
- hosts: master
  become: true
  remote_user: root
  tasks:

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Kubespray repository
      git:
        repo: "https://github.com/kubernetes-sigs/kubespray.git"
        dest: "/home/ubuntu/kubespray"
        version: "master"
        
    # Обновление индекса пакетов
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - python3-dev
          - libffi-dev
          - libssl-dev
          - libyaml-dev
          - virtualenv
        state: present

    - name: Install Kubespray dependencies
      pip:
        requirements: "/home/ubuntu/kubespray/requirements.txt"
        executable: pip3
      become: true
      
    - name: Copy inventory file
      command: cp -rfp /home/ubuntu/kubespray/inventory/sample /home/ubuntu/kubespray/inventory/mycluster
      become: true

    - name: Set fact for IPS
      set_fact:
        IPS: ["10.0.1.10", "10.0.1.11", "10.0.1.12"]
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Execute the inventory.py command
      command: "python3 /home/ubuntu/kubespray/contrib/inventory_builder/inventory.py {{ IPS | join(' ') }} --config-file=/home/ubuntu/kubespray/inventory/mycluster/hosts.yaml"
      args:
        chdir: /home/ubuntu/kubespray
      become: true

    - name: Move hosts.yaml to Kubespray inventory
      command: mv /home/ubuntu/hosts.yaml /home/ubuntu/kubespray/inventory/mycluster/
      become: true

    - name: Execute Kubespray on master
      ansible.builtin.command:
        cmd: "ansible-playbook -i /home/ubuntu/kubespray/inventory/mycluster/hosts.yaml /home/ubuntu/kubespray/cluster.yml -b"
        chdir: /home/ubuntu/kubespray
#      async: 2000  # Устанавливаем максимальное время выполнения в секундах (например, 600 секунд)
#      poll: 0    # Ожидаем завершения задачи

