---
- hosts: all
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Kubespray repository
      git:
        repo: "https://github.com/kubernetes-sigs/kubespray.git"
        dest: "/home/ubuntu/kubespray"
        version: "master"

    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - python3-dev
          - libffi-dev
          - libssl-dev
          - libyaml-dev
          - python3
          - virtualenv
        state: present

    - name: Install Kubespray dependencies
      pip:
        requirements: "/home/ubuntu/kubespray/requirements.txt"
        executable: pip3
      become: true
      
    - name: Copy inventory file
      command: cp -rfp ~/kubespray/inventory/sample ~/kubespray/inventory/mycluster
      become: false

    - name: Configure Kubespray inventory
      lineinfile:
        path: "/home/ubuntu/kubespray/inventory/mycluster/inventory.ini"
        regexp: '^(kube_network_plugin: )'
        line: 'kube_network_plugin: calico'
      become: false

    - name: Run Kubespray
      command: |
        ansible-playbook -i ~/kubespray/inventory/mycluster/inventory.ini --become --become-user=root ~/kubespray/cluster.yml
      become: false
